### ISSUE TITLE
Is unified syntax possible?

### ISSUE THREAD

**Issue by bearoutthere** [bradleygore/nativescript-textinputlayout#35]
Hello,
i've read through the documentation and the previous issues.  Everything i've read appears to point to the fact that the XML markup for Android is Different than for iOS (inclusion or exclusion of the child TextField).  Since i have a few dozen fields, conditionally duplicating markup by OS would be rather clunky. It would be preferable to use the same syntax for both.

Is there a recommended way to create a page suitable for both platforms and to minimize code repetition?  Would something like below work?   Do TextField properties set on TextInputLayout (as prescribed for iOS) trickle down to the child TextField component (as prescribed for Android)?

```
<TIL:TextInputLayout
    hint="{{ hint }}"
    isEnabled="{{ isEnabled }}"
    disabledColor="#c3c3c3"
    error="{{ error }}"
    text="{{ demoText }}"
    title="{{ title }}"
    color="{{ error ? '#aa0000' : '#d745ff' }}"
    tintColor="#d745ff"
    lineColor="#d745ff"
    selectedTitleColor="#ff45ca"
    selectedLineColor="#7a45ff"
    lineHeight="1.25"
    selectedLineHeight="3.5" >

<android>
       <TextField text="{{ demoText }}" />
</android>

</TIL:TextInputLayout>

```

Thanks in advance.

**Comment by bearoutthere** [comment]
And lastly is it possible to use masked text field plugin with this one? https://github.com/PeterStaev/nativescript-masked-text-field

It seems to be working with Android since  it allows for a separate TextField element.  But not for iOS.  

Is it possible to standardize the syntax to use the single version with the TextField for both OSs?

**Comment by bradleygore** [comment]
I no longer actively maintain this project (see updated readme).

*Unified syntax*: No, not possible in my experience. When I first attempted to build the plugin, I was hoping so you would't have to nest a `<TextField>` in the android version - but I couldn't get the NativeScript-provided property bindings (text, etc...) to work right. So, you have to explicitly define your TextField that goes inside the TextInputLayout wrapper in android. For iOS, the SkyFloatingLabelTextField actually extends the iOS-equivalent of TextField, vs having one added to it, so it works entirely differently. The underlying components that this plugin facades over are android-specific and iOS-specific... and they work entirely differently.

PRs are welcome if you come up with something otherwise.

**Comment by bearoutthere** [comment]
Thanks Bradley,

here's what i ended up doing for the masked field:

```
<til:TextInputLayout    name="postalCode" hint="Postal code" text="" returnKeyType="next" keyboardType="number" autocorrect="false"  focus="onFocus" blur="onBlur" class="" id="postalCode" error="{{ error }}" errorEnabled="true" >
        <android>
              <mtf:MaskedTextField   name="postalCode" hint="Postal code" text="" returnKeyType="next" keyboardType="number" autocorrect="false"  focus="onFocus" blur="onBlur" class="" mask="00000"/>
        </android>
</til:TextInputLayout>
```

Some properties have to be repeated to support both OSs.  And MaskedTextField plugin works for Android.  iOS users will have to do without for now.  

Thanks for making your plugin available to the community.
