### ISSUE TITLE
Textfield properties not evaluated on iOS

### ISSUE THREAD

**Issue by andreacappadona17** [bradleygore/nativescript-textinputlayout#9]
Hello, is there any way to use Texfield properties like "secure", "autocapitalizationType" or "autocorrect" with this plugin on iOS?
They are working just fine on Android, when using them on the child element.

Thanks

**Comment by jevenson** [comment]
To expand on this, I'm not able to use the simple "text" property to set an initial text of the element.

**Comment by bradleygore** [comment]
@jevenson the README shows a demo of it working with the text property and binding as it should. Unless some update (either iOS or {N} or the plugin) changed something, it should work as shown in the demo. Otherwise, I'm not sure and I'm not doing any native development at this time so it will be quite a while before I can get to digging into it.

**Comment by priyangamani** [comment]
Textfield  secure property[secure="true"] is not working in ios with this plugin

**Comment by bradleygore** [comment]
@andreacappadona17 @jevenson @priyangamani - please check out the latest update - [v2.0.2](https://github.com/bradleygore/nativescript-textinputlayout/commit/6013350a008202b4769f5347c4e79933c5b53e85), this should be fixed. Also, please see the updated `README` and demo graphic for iOS.
